from fastapi.testclient import TestClient

from app.main import app
from app.api.v1.consulting import agent
from app.auth.dependencies import get_current_user

client = TestClient(app)

def fake_current_user():
    return {
    "user_id": 1,
    "email": "[test@example.com](mailto:test@example.com)",
    "role": "user",
    }

def fake_consulting(
question,
context,
sources="",
    ):
    return (
    "This is a test consulting analysis "
    "generated by the mocked ConsultingAgent."
    )

def test_consulting_api():
    app.dependency_overrides[
    get_current_user
    ] = fake_current_user


    original_analyze = agent.analyze
    agent.analyze = fake_consulting

    try:
        response = client.post(
            "/api/v1/consulting/",
            json={
                "question": (
                    "Should a company expand "
                    "into the Indian EV market?"
                ),
                "context": (
                    "The Indian EV market is growing "
                    "and competition is increasing."
                ),
                "sources": (
                    "Example Research - "
                    "https://example.com"
                ),
            },
        )
    finally:
        agent.analyze = original_analyze
        app.dependency_overrides.clear()

    assert response.status_code == 200

    data = response.json()

    assert (
        data["question"]
        == "Should a company expand "
        "into the Indian EV market?"
    )

    assert "analysis" in data
    assert data["analysis"] != ""


def test_consulting_empty_question():
    app.dependency_overrides[
    get_current_user
    ] = fake_current_user

    try:
        response = client.post(
            "/api/v1/consulting/",
            json={
                "question": "",
                "context": "Some research evidence.",
            },
        )
    finally:
        app.dependency_overrides.clear()

    assert response.status_code == 422


def test_consulting_empty_context():
    app.dependency_overrides[
    get_current_user
    ] = fake_current_user


    try:
        response = client.post(
            "/api/v1/consulting/",
            json={
                "question": "Should we expand?",
                "context": "",
            },
        )
    finally:
        app.dependency_overrides.clear()

    assert response.status_code == 422

