from fastapi.testclient import TestClient

from app.main import app
from app.api.v1.research import agent
from app.auth.dependencies import get_current_user


client = TestClient(app)


def fake_current_user():
    return {
        "user_id": 1,
        "email": "test@example.com",
        "role": "user",
    }


def fake_research(
    question,
    document_id=None,
    top_k=5,
):
    return (
        "This is a test research answer "
        "generated by the mocked ResearchAgent."
    )


def test_research_api():

    app.dependency_overrides[
        get_current_user
    ] = fake_current_user

    original_answer = agent.answer
    agent.answer = fake_research

    response = client.post(
        "/api/v1/research/",
        json={
            "question": "What is HAC?",
            "document_id": 7,
            "top_k": 5,
        },
    )

    agent.answer = original_answer

    app.dependency_overrides.clear()

    assert response.status_code == 200

    data = response.json()

    assert data["question"] == "What is HAC?"
    assert data["document_id"] == 7
    assert "answer" in data
    assert data["answer"] != ""


def test_research_empty_question():

    app.dependency_overrides[
        get_current_user
    ] = fake_current_user

    response = client.post(
        "/api/v1/research/",
        json={
            "question": "",
        },
    )

    app.dependency_overrides.clear()

    assert response.status_code == 422