from typing import Any
from app.tools.retrieval_tool import retrieval_tool
from app.tools.web_search_tool import web_search_tool
from app.tools.yahoo_finance_tool import yahoo_finance_tool


class ToolExecutorService:
    """
    Executes tools selected by ToolRouterService.

    Responsibilities:
    - Map validated tool names to actual tools
    - Execute the selected tool with supplied arguments
    - Handle direct_answer without tool execution
    - Return a consistent execution result

    This service does NOT decide which tool should be used.
    Tool selection remains the responsibility of ToolRouterService.
    """

    def __init__(self) -> None:
        self._tools = {
            "retrieval_tool": retrieval_tool,
            "web_search_tool": web_search_tool,
            "yahoo_finance_tool": yahoo_finance_tool,
        }

    def execute(
        self,
        tool_name: str,
        arguments: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Execute a tool selected by the ToolRouterService.

        Args:
            tool_name: Name of the tool selected by the router.
            arguments: Arguments generated by the router.

        Returns:
            Structured execution result.
        """

        arguments = arguments or {}

        # ---------------------------------------------------------
        # Direct answer requires no external tool execution.
        # ---------------------------------------------------------
        if tool_name == "direct_answer":
            return {
                "success": True,
                "tool": "direct_answer",
                "executed": False,
                "evidence": None,
                "error": None,
            }

        # ---------------------------------------------------------
        # Security boundary:
        # Only explicitly registered tools can be executed.
        # ---------------------------------------------------------
        tool = self._tools.get(tool_name)

        if tool is None:
            return {
                "success": False,
                "tool": tool_name,
                "executed": False,
                "evidence": None,
                "error": f"Unsupported tool: {tool_name}",
            }

        # ---------------------------------------------------------
        # Execute the selected LangChain @tool.
        # ---------------------------------------------------------
        try:
            result = tool.invoke(arguments)

            return {
                "success": True,
                "tool": tool_name,
                "executed": True,
                "evidence": result,
                "error": None,
            }

        except Exception as exc:
            return {
                "success": False,
                "tool": tool_name,
                "executed": True,
                "evidence": None,
                "error": str(exc),
            }